const keywords = {
  "Long Shot": "While attacking, spend up to X aim tokens to increase this weapon's maximum range by 1 for each aim tkoen spent.",
  "Small": "While defending, when determining line of sight, cover, and range, ignore this mini.",
  "Marksman": "While attacking, you can spend aim tokens to improve attack die results.",
  "Covert Ops": "When you deploy, you may treat your rank as Operative. If you do, gain INFILTRATE.",
  "Loadout": "When you deploy, you may swap any of your equipped upgrades with your set-aside upgrades.",
  "Incognito": "You cannot be attacked by enemy units beyond range 1, unless you have performed an attack or used an objective card action during this game.",
  "Skirmish": "Intended for use in Skirmish matches.",
  "Low Profile": "While defending, if you have light cover, improve your cover by 1.",
  "Generator": "During the End Phase, flip X inactive shield token(s).",
  "Agile": "After you perform a standard move, gain X dodge token(s). Note: climbing, clambering, embarking, disembarking, pivoting, and reversing are not standard moves. This effect does not trigger abilities that occur after dodge actions are performed.",
  "Compel": "After another friendly unit at range 1-2 rallies, if it is suppressed but not panicked, it may gain 1 suppression token to perform a free move action.",
  "Transport: Closed": "You may transport up to X friendly trooper units.",
  "Immune": "X cannot be used against you.",
  "Creature Trooper": "You can: obscure other minis and provide light cover while doing so, pivot and reverse, displace troopers when moving through them. You do not: improve your cover while you have 1 or more suppression tokens, get cover from barricades, embark or disembark, use CLAIM/SABOTAGE/REPAIR abilities, be displaced",
  "Vehicle": "You can: pivot, block line of sight. Ground vehicles can: reverse, move through repulsor vehicles, perform the standby action, obscure other minis and provide cover. Repuslor vehicles: can move through troopers and vehicles.",
  "Surge Token": "Spending one or more surge tokens will convert the same number of surges to blocks while defending or using using GUARDIAN, and to hits while attacking.",
  "Speeder": "While moving, ignore terrain that is height X or lower. When you activate, perform a compulsory move.",
  "Hover": "You can reverse, strafe, and standby. You are treated as a ground vehicle by other units.",
  "Heavy Weapon Team": "You must equip a Heavy Weapon upgrade card. The mini added by that card is your unit leader.",
  "Nimble": "After defending, if you spent 1 or more dodge tokens, gain 1 dodge token.",
  "Indomitable": "During your Rally step, roll red defense dice instead of white.",
  "Versatile": "You can perform ranged attacks using this weapon while engaged.",
  "Cunning": "When your commander-specific command cards are played, if there would be a tie for priority, treat your command card as though it had 1 fewer pip.",
  "Reposition": "Either before or after you perform a standard move, you may perform a free pivot action.",
  "Sidearm": "While performing a melee attack, this mini can only use the weapon on this card.",
  "Enrage": "While you have 4 or more wound tokens, treat your courage as \"-\" and gain CHARGE.",
  "Fixed": "The defender must be inside your X arc(s).",
  "Full Pivot": "When you pivot, you can pivot up to 360 degrees.",
  "Entourage": "While building an army, ignore the rank of 1 X unit. During the Command Phase, you may issue an order to a friendly X unit at range 1-2.",
  "Ion Token": "At the start of a unit's activation, if it has 1 or more ion tokens, it loses one action for each ion token. At the end of a unit's activation, it removes any ion tokens it has. A unit may still perform free actions if it loses both of its actions due to ion tokens.",
  "Ram": "While you perform an attack, during the \"Modify Attack Dice\" step, you may change X attack die results to crit results if you performed at least 1 full standard move at max speed during the same activation as the attack.",
  "Spotter": "Choose X friendly unit at range 1. That unit gains an aim token.",
  "Sentinel": "Your standby range is 1-3.",
  "Arm": "Place X of the specified charge tokens within range 1 and in line of sight of your unit leader.",
  "Recharge": "When you recover, flip up to X inactive shield tokens to their active side.",
  "Impact": "While attacking a unit that has ARMOR, change up to X hit results to crit results.",
  "Gunslinger": "After you perform a ranged attack, you may perform an additional ranged attack against a different unit.",
  "Regenerate": "At the end of your activation, roll 1 white defense die for each wound token you have, up to X. For each defense surge or block result, remove 1 wound token.",
  "Danger Sense": "You may choose not to remove your suppression tokens. While defending against a ranged attack, roll 1 extra defense die for each suppression token you have, adding up to X extra dice.",
  "Makashi Mastery": "While performing a melee attack, you may reduce the PIERCE value of your melee weapon by 1. If you do, the defender cannot use IMMUNE: PIERCE or IMPERVIOUS.",
  "Demoralize": "After your Rally step, an enemy unit at range 1-2 gains up to X suppression tokens.",
  "Emplacement Trooper": "You can: obscure other minis and provided light cover when doing so, pivot. You cannot: climb or clamber, use CLAIM/SABOTAGE/REPAIR, be displaced, be moved through by ground vehicles.",
  "Graffiti Token": "During the Rally step of a friendly unit's activation: if it has line of sight to a friendly graffiti token at range 1-2, it may roll 1 additional die; if it has line of sight to an enemy graffiti token at range 1-2, it must roll 1 fewer die, to a minimum of 1.",
  "Uncanny Luck": "While defending, you may reroll up to X defense dice.",
  "Ion": "A vehicle or droid wounded by an attack that includes this weapon gains X ion tokens. At the start of the Roll Defense Dice step, before any other effects, if the attack pool has ION X, for each hit or critical result, up to X, the defender must flip an active shield token without resolving its effect, if able.",
  "Barrage": "If you do not use ARSENAL during your activation, you can perform up to 2 attack actions.",
  "Soresu Master": "While defending or using GUARDIAN, if you spend a dodge token, you gain surge to block and the attacker suffers 1 wound for each surge rolled.",
  "Spur": "While performing a move, you may gain 1 suppression token to increase your maximum speed by 1.",
  "Pulling the Strings": "Choose a friendly trooper unit at range 1-2. That unit may perform a free attack action or a free move action.",
  "Target": "After you are issued an order, gain X aim tokens.",
  "Cover": "While defending against a ranged attack, improve your cover by X.",
  "Distract": "Choose an enemy trooper at range 1-2 and in line of sight. Until the end of the round, you lose INCONSPICUOUS and when that unit performs an attack, it must attack you, if able.",
  "Weak Point": "While defending, if the attacker's unit leader is inside your X arc(s), the attack pool gains IMPACT 1.",
  "Ready": "After you perform a standby action, gain 1 aim token.",
  "Smoke": "Place X smoke token(s) within range 1 and in line of sight of your unit leader.",
  "Stationary": "You cannot perform moves, except pivots.",
  "Block": "While defending, if you spend a dodge token, you gain surge to block.",
  "Precise": "When you spend an aim token, reroll up to X additional dice.",
  "Disengage": "You may perform moves while engaged with 1 unit.",
  "Inspire": "After your Rally step, remove up to X suppression tokens from another friendly unit at range 1-2.",
  "Arsenal": "While attacking, each mini in this unit can use up to X of its weapons.",
  "Jump": "Perform a move during which you ignore terrain that is height 1 or lower. This is treated as a move action.",
  "Jedi Hunter": "While attacking a unit that has a Force upgrade icon, you gain surge to crit.",
  "Shield Token": "While defending against a ranged attack, during the Roll Defense Dice step, before rolling defense dice, you may flip any number of active shield tokens. For each shield token flipped this way, the defender adds 1 block result and rolls 1 fewer defense die.",
  "Dauntless": "After you rally, if you are suppressed but not panicked, you may gain 1 suppression token to perform a free move action.",
  "Defend": "When you are issued an order, you may gain X dodge tokens.",
  "Critical": "While converting attack surges, you may convert up to X surge results to critical results.",
  "Treat": "Place a wound token on this card to choose a friendly trooper unit at range 1 and in line of sight and remove up to X wound or poison tokens from that unit or restore up to X miniatures to that unit. Limit Y tokens.",
  "Suppressive": "After you perform an attack, the defender that this weapon was used against gains 1 suppression token.",
  "Leader": "This mini is your unit leader.",
  "Guardian": "While a friendly trooper unit at range 1 and in line of sight is defending against a ranged attack, you may cancel up to X hit results. For each result canceled, roll 1 of your defense dice. Convert any surges, then suffer 1 wound for each blank result.",
  "Outmaneuver": "You can spend dodge tokens to cancel critical hit results.",
  "Armor": "While defending, cancel up to X hit results.",
  "Scout": "After you deploy, you may perform a speed-X move.",
  "Wheel Mode": "When you activate, you may increase your maximum speed to 3. If you do, until the end of the round, you gain COVER 2 and cannot attack or flip active shield tokens. This is a free action that can only be done at the start of this unit's activation.",
  "Unhindered": "You ignore the effects of difficult terrain.",
  "Expert Climber": "While clambering, do not roll defense dice or suffer wounds.",
  "Blast": "Ignore cover.",
  "Inconspicuous": "While an enemy unit performs an attack, if you have at least one suppression token, it must attack another unit, if able. During your Rally step, you may choose not to remove your suppression tokens.",
  "Steady": "After you perform a move action, you may perform a free ranged attack action.",
  "Detonate": "After a unit controlled by any player performs an action, you may detonate X of the friendly specified charge tokens.",
  "Tactical": "After you perform a standard move, gain X aim tokens.",
  "Coordinate": "After you are issued an order, you may issue an order to a friendly unit with the name or type specified by X at range 1.",
  "Scatter": "After performing an attack against a trooper unit with small bases, you may move any non-leader minis in the defending unit, following the all the rules of cohesion, as if the unit leader had performed a standard move.",
  "Repair": "Place a wound token on this card to remove up to X wound, ion, or vehicle damage tokens from a friendly vehicle at range 1 and in line of sight. Limit Y tokens.",
  "Droid Trooper": "Droid troopers do not lose actions and do not gain cover from suppression. Droids can still become panicked due to suppression, however.",
  "Tow Cable": "After a vehicle is wounded by an attack that includes this weapon, perform a pivot with that vehicle.",
  "Charge": "After you perform a move action, you may perform a free melee attack action.",
  "Disciplined": "When you are issued an order, you may remove up to X suppression tokens.",
  "Secret Mission": "Once per game, if you are within an enemy deployment zone, place 1 victory token on you. At the end of the game, if you have a victory token, gain that token.",
  "Teamwork": "While you are at range 1-2 of X, when you or X gains an aim or dodge token, the other unit gains a token of the same type.",
  "Plodding": "During your activation, you can perform only 1 standard move.",
  "Poison Token": "At the end of a unit's activation, it suffers 1 wound for each poison token it has, then discards each poison token it has. Vehicles and droid trooper units cannot gain poison tokens.",
  "Grounded": "You cannot climb or clamber.",
  "Light Transport: Closed": "You may transport X friendly trooper units that consists of exactly 1 small base mini.",
  "Calculate Odds": "Choose a friendly trooper unit at range 1 and in line of sight. It gains 1 aim, 1 dodge, and 1 suppression token",
  "Bounty": "After setup, place a victory token on an enemy commander or operative. If you defeat a unit with a victory token, move that token to your. At the end of the game, if you have a victory token, gain that token.",
  "Master of the Force": "During the End Phase, you may ready X of your Force upgrade cards.",
  "Deflect": "While defending, if you spend a dodge token, any defense surge results are converted to block results; if it's a ranged attack, the attacker suffers 1 wound for each defense surge rolled.",
  "Spray": "Add this weapon's dice to the attack pool one time for each mini in the defending unit to which line of sight is not blocked.",
  "Detachment": "During army building, you may only be included if a unit that has the name or type specified by X is also included in your army. Each unit with the DETACHMENT keyword requires a corresponding unit that matches the unit name or type specified.",
  "Reconfigure": "When you recover, you may flip this card.",
  "Infiltrate": "You may deploy anywhere beyond range 3 of all enemy units.",
  "Pierce": "While attacking, cancel up to X block results.",
  "Shielded": "You have X shield tokens.",
  "Sharpshooter": "While performing a ranged attack, reduce the defneder's cover by X.",
  "Counterpart": "While building an army, this mini must be added to an X unit.",
  "Take Cover": "Choose X friendly trooper units at range 1. That unit gains a dodge token.",
  "Relentless": "After you perform a move action, you may perform 1 free attack action.",
  "Impervious": "While defending, if the attack pool has PIERCE X, roll X additional defense dice.",
  "Noncombatant": "This mini cannot use any weapons and wounds must be assigned to other non-unit leader minis first.",
  "Transport: Open": "You may transport up to X friendly trooper units. After defending, if you suffered 1 or more wounds, each unit you are transporting suffers 1 wound.",
  "High Velocity": "While attacking, if each weapon in your attack pool has HIGH VELOCITY, the defender cannot spend dodge tokens.",
  "Climbing Vehicle": "You are treated as a trooper for the purposes of vertical movement.",
  "Quick Thinking": "Gain 1 aim token and 1 dodge token.",
  "AI": "Unless you have a faceup order token, your first action must be one of the following, if able: X",
  "Light Transport: Open": "You may transport X friendly trooper units that consists of exactly 1 small base mini. After defending, if you suffered 1 or more wounds, each unit you are transporting suffers 1 wound.",
  "Cumbersome": "You cannot use this weapon and move during the same activation.",
  "Fire Support": "When another friendly unit performs a ranged attack, if you have a faceup order token, each mini in your unit may add an eligible weapon to the attack pool. If you do, flip your order token facedown. Limit 1 FIRE SUPPORT per attack pool. Note: Can still be used even if a unit would panic during its activation. Only the main unit attacking determines cover, LoS, and surges.",
  "Beam": "After performing an attack with this weapon, you may perform up to 2 extra attacks using only this weapon. Each attack must be against an enemy unit that is in line of sight, has not already defended, and is at range 1 of the defender.",
  "Cycle": "At the end of your activation, if you did not use this card, ready it."
};

export default keywords;
